<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>VideoLibrarySystemVlc</AssemblyName>
    <RootNamespace>VideoLibrarySystemVlc</RootNamespace>
    <ApplicationIcon>Assets\videotape.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Images\mascoss\BaseNoSas.jpg" />
    <None Remove="Images\mascoss\mascost.jpg" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="ResourceDictionaries\" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\mascoss\BaseNoSas.jpg" />
    <Resource Include="Images\mascoss\mascost.jpg" />
    <Resource Include="SampleData\fallback-collectibles.json" />
  </ItemGroup>
</Project>
